/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "includes/Protobuf/data_def_v0_pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Timestamp, Timestamp, AUTO)


PB_BIND(Position, Position, AUTO)


PB_BIND(InputValue, InputValue, AUTO)


PB_BIND(Event, Event, AUTO)


PB_BIND(MQTTConfiguration, MQTTConfiguration, AUTO)


PB_BIND(AnalogInputConfiguration, AnalogInputConfiguration, AUTO)


PB_BIND(DigitalInputConfiguration, DigitalInputConfiguration, AUTO)


PB_BIND(TemperatureInputConfiguration, TemperatureInputConfiguration, AUTO)


PB_BIND(InputData, InputData, AUTO)


PB_BIND(History, History, 2)


PB_BIND(Events, Events, AUTO)


PB_BIND(Statistics, Statistics, 2)


PB_BIND(InputConfiguration, InputConfiguration, 2)


PB_BIND(Configuration, Configuration, 2)


PB_BIND(UplinkMessage, UplinkMessage, 2)








